apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: states
  template:
    metadata:
      labels:
        app: states
    spec:
      containers:
      - name: states
        image: kaustubhk29/kaniko:latest
        resources:
          requests:
            memory: "50Mi"
            cpu: "40m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
